version: 1.2.1
release_notes: |
  * Cleaned up code; updated spk.yaml file with latest Maya variant and Release compiler flag.

toolchain: []

components:
  # libs:
  - kind: SPKPackage
    name: maya-spreticleloc
    spec_file: spreticleloc.spk.yaml
