version: 2.1.0
release_notes: |
  * Merged/rebased with external github site: https://github.com/imageworks/spReticle

toolchain: []

components:
  # libs:
  - kind: SPKPackage
    name: maya-spreticleloc
    spec_file: spreticleloc.spk.yaml
