version: 1.1.3
release_notes: |
  * Rebuilding for spk conflict and cleaning maya variants

toolchain: []

components:
  # libs:
  - kind: SPKPackage
    name: maya-spreticleloc
    spec_file: spreticleloc.spk.yaml
