<<<<<<< HEAD
version: 1.2.0
release_notes: |
  * Fixed AEspReticleLocTemplate.mel install dir; updated maya-platform.

toolchain: []

components:
  # libs:
  - kind: SPKPackage
    name: maya-spreticleloc
    spec_file: spreticleloc.spk.yaml
