version: 1.1.0
release_notes: |
  * Fixed plugin name: removed leading 'lib'.

toolchain: []

components:
  # libs:
  - kind: SPKPackage
    name: maya-spreticleloc
    spec_file: spreticleloc.spk.yaml
